-- START_DATE, END_DATE가 있을 때, 특정 날짜가 해당 기간에 포함되는지 알아내기
-- CASE ~ WHEN ~ THEN ~ ELSE ~ END
-- CASE WHEN 조건 1 THEN 결과 1
--      WHEN 조건 2 THEN 결과 2
--      THEN 결과 3
--      ELSE 결과 4
-- END AS 별명
SELECT CAR_ID, MAX(CASE WHEN '2022-10-16' BETWEEN  DATE_FORMAT(START_DATE, '%Y-%m-%d') AND  DATE_FORMAT(END_DATE, '%Y-%m-%d') THEN '대여중'
ELSE '대여 가능' END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;